language: php
php:
    0: 7.1
    1: 5.6
    2: 7
    4: hhvm
dist: trusty
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - 'composer install --no-interaction'
    - './vendor/bin/hidev --version'
    - './vendor/bin/hidev travis/before-install'
matrix:
    allow_failures:
        -
            php: hhvm
sudo: false
install:
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after-script'
